# Generated by Django 5.1 on 2024-11-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idCategoria')),
                ('Nombre', models.CharField(max_length=1000, verbose_name='Nombre')),
                ('idProducto', models.CharField(max_length=100, verbose_name='idProducto')),
                ('Promociones', models.CharField(max_length=100)),
                ('Tamaño', models.CharField(max_length=100, verbose_name='Tamaño')),
                ('Color', models.CharField(max_length=100, verbose_name='Color')),
                ('Genero', models.CharField(max_length=100, verbose_name='Genero')),
            ],
        ),
    ]
