# Generated by Django 5.1 on 2024-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='idProducto',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='idCategoria'),
        ),
    ]
