# Generated by Django 5.1 on 2024-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProductos', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=1000)),
                ('Precio', models.CharField(max_length=100)),
                ('idCategoria', models.CharField(max_length=6)),
                ('idProvedores', models.CharField(max_length=6)),
                ('Descripcion', models.CharField(max_length=100)),
                ('CantidadStock', models.CharField(max_length=100)),
            ],
        ),
    ]
