# Generated by Django 5.1 on 2024-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idProveedor')),
                ('Nombre', models.CharField(max_length=1000, verbose_name='Nombre')),
                ('Telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('Correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('TipoProducto', models.CharField(max_length=100, verbose_name='Tipo de producto')),
            ],
        ),
    ]
