# Generated by Django 5.1 on 2024-11-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idEmpleados', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=1000)),
                ('Telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Turno', models.CharField(max_length=100)),
                ('Sueldo', models.CharField(max_length=100)),
                ('Puesto', models.CharField(max_length=100)),
            ],
        ),
    ]
