# Generated by Django 5.1 on 2024-11-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('idOrdenes', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='idOrdenes')),
                ('idClientes', models.CharField(max_length=1000, verbose_name='idClientes')),
                ('FechaOrden', models.DateField(verbose_name='Fecha de orden')),
                ('Cantidad', models.CharField(max_length=100)),
                ('FechaEnvio', models.DateField(verbose_name='Fecha de envio')),
                ('DireccionEnvio', models.CharField(max_length=100, verbose_name='Direccion de envio')),
                ('idEmpleado', models.CharField(max_length=100, verbose_name='idEmpleado')),
                ('idProducto', models.CharField(max_length=100, verbose_name='idProductos')),
            ],
        ),
    ]
