# Generated by Django 5.1 on 2024-11-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idClientes', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='idClientes')),
                ('Nombre', models.CharField(max_length=1000, verbose_name='Nombre')),
                ('Telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('Direccion', models.CharField(max_length=1000, verbose_name='Direccion')),
                ('Correo', models.EmailField(max_length=1000, verbose_name='Correo')),
                ('FechaRegistro', models.DateField(verbose_name='Fecha de registro')),
            ],
        ),
    ]
